spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/cn_hotel"
    username: "postgres"
    password: "0000"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
